token: 'DISCORD-TOKEN-HERE'
channels:
  - 1136727282938019880
  - 1136727312793083985
  - 1136727376047390781
  - 1136727411145330868
games:
  articles:
    - 'مالي اراك حزينا احرمت من الجنة ام بشرت بالنار'
    - 'ما يركز على أن المعرفة تبدأ بالاعتراف بالجهل وأن العلم يسعى إلى الأسباب الأولى للوجود'
  dismantle:
    - 'سكار'
    - 'فلسطين'
  dismantling:
    - 'يتم الجنون'
    - 'سكار يخطط لإنقلاب'
    - 'مدير الكروب يسوي كذا'
  fast:
    - 'سكار حبوب'
  flags:
    - 'باكستان|https://media.discordapp.net/attachments/991426456938872853/1136722188137926746/437178805677981696.png'
  sentences:
    - 'من طلب العلا سهر الليالي'
  translate:
    - 'doctor|دكتور|طبيب'
